language: node_js
sudo: false
node_js:
  - "9"
install:
  - npm install -g @angular/cli
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - cd $TRAVIS_BUILD_DIR/server
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/client
  - npm test