dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "9"
sudo: false
install:
  - npm install -g @angular/cli
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - cd $TRAVIS_BUILD_DIR/server
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/client
  - npm test