language: node_js
node_js:
  - "8"
sudo: true
install:
  - npm install -g @angular/cli
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - cd $TRAVIS_BUILD_DIR/server
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/client
  - npm test