dist: xenial
addons:
  chrome: stable
language: node_js
node_js:
  - "10"
sudo: false
install:
  - npm install -g @angular/cli
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - cd $TRAVIS_BUILD_DIR
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/client
  - npm test
  - cd $TRAVIS_BUILD_DIR
  - tsc
  - npm test